apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: testprojectpolicy
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: testnamespace
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: testprojectpolicy-placement
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: In
              values:
                - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: testprojectpolicy-placement
  namespace: default
placementRef:
  name: testprojectpolicy-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: testprojectpolicy
    apiGroup: policy.open-cluster-management.io
    kind: Policy

