apiVersion: apps.open-cluster-management.io/v1
kind: Placement
metadata:
  labels:
    app: httpd
  name: cluster1only
  namespace: simple-app
spec:
  clusterSelector:
    matchLabels:
      env: testing
  clusterReplicas: 1
