apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: test-secret     
  namespace: simple-app  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - test-secret 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription

