apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: simple-config     
  namespace: simple-app  
spec:
  matchExpressions:
  - key: app  
    operator: In
    values:
    - simple-config-1
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription

