apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: test-secret     
  namespace: simple-app  
spec:
  selector:
    matchLabels:
      app: test-secret-1
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription

