apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: test-secret                           
  namespace: simple-app
  labels:
    app: test-secret
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-lab-matchlabels-03332345-assets
spec:
  channel:  simple-app/test-secret-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: test-secret-placement
[mlele@mlele lab-matchlabels-03332345]$ cat channel.yaml 
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: test-secret-channel
  namespace: simple-app
spec:
  secretRef:
    name: git-ssh-key
  pathname: 'https://github.com/mihirlele/rhacmgitopslab.git'
  type: GitHub

